In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
dataset = pd.read_csv('train.csv')
X = dataset.loc[:,['Pclass', 'Sex', 'Age', 'SibSp', 'Parch','Embarked']]
#'PassengerId',
dataset

PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch Cabin Embarked
0              1         0       3    male  22.0      1      0   NaN        S
1              2         1       1  female  38.0      1      0   C85        C
2              3         1       3  female  26.0      0      0   NaN        S
3              4         1       1  female  35.0      1      0  C123        S
4              5         0       3    male  35.0      0      0   NaN        S
..           ...       ...     ...     ...   ...    ...    ...   ...      ...
886          887         0       2    male  27.0      0      0   NaN        S
887          888         1       1  female  19.0      0      0   B42        S
888          889         0       3  female   NaN      1      2   NaN        S
889          890         1       1    male  26.0      0      0  C148        C
890          891         0       3    male  32.0      0      0   NaN        Q

[891 rows x 9 columns]

In [3]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X.iloc[:,1] = le.fit_transform(X.iloc[:,1])

In [4]:
X

Pclass  Sex   Age  SibSp  Parch Embarked
0         3    1  22.0      1      0        S
1         1    0  38.0      1      0        C
2         3    0  26.0      0      0        S
3         1    0  35.0      1      0        S
4         3    1  35.0      0      0        S
..      ...  ...   ...    ...    ...      ...
886       2    1  27.0      0      0        S
887       1    0  19.0      0      0        S
888       3    0   NaN      1      2        S
889       1    1  26.0      0      0        C
890       3    1  32.0      0      0        Q

[891 rows x 6 columns]

In [5]:
X.Embarked.notnull()

0      True
1      True
2      True
3      True
4      True
       ... 
886    True
887    True
888    True
889    True
890    True
Name: Embarked, Length: 891, dtype: bool

In [6]:
X.Embarked.notnull() == True

0      True
1      True
2      True
3      True
4      True
       ... 
886    True
887    True
888    True
889    True
890    True
Name: Embarked, Length: 891, dtype: bool

In [7]:
X.iloc[61,5]

nan

In [8]:
lst = (X.iloc[:,5] != 'nan')
print(len(lst))

891


In [9]:
dataset.shape

(891, 9)

In [10]:
#changing the null values from the age to the mean of the age data
X['Age'] = X['Age'].fillna(X['Age'].median())
X

Pclass  Sex   Age  SibSp  Parch Embarked
0         3    1  22.0      1      0        S
1         1    0  38.0      1      0        C
2         3    0  26.0      0      0        S
3         1    0  35.0      1      0        S
4         3    1  35.0      0      0        S
..      ...  ...   ...    ...    ...      ...
886       2    1  27.0      0      0        S
887       1    0  19.0      0      0        S
888       3    0  28.0      1      2        S
889       1    1  26.0      0      0        C
890       3    1  32.0      0      0        Q

[891 rows x 6 columns]

In [11]:
#removing all the null values from the emarked column
for i in range(891):
    if X['Embarked'][i] not in ['S', 'C', 'Q']:
        X.loc[i,'Embarked'] = 'S'
X.Embarked = X.Embarked.astype(str)

In [12]:
emb = LabelEncoder()
X.iloc[:,5] = emb.fit_transform(X.iloc[:,5])
X

#Performing OneHotEncoding on Embarked
#from sklearn.compose import ColumnTransformer
#from sklearn.preprocessing import OneHotEncoder
#ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [6])], remainder='passthrough')
#X = np.array(ct.fit_transform(X))
#X

Pclass  Sex   Age  SibSp  Parch  Embarked
0         3    1  22.0      1      0         2
1         1    0  38.0      1      0         0
2         3    0  26.0      0      0         2
3         1    0  35.0      1      0         2
4         3    1  35.0      0      0         2
..      ...  ...   ...    ...    ...       ...
886       2    1  27.0      0      0         2
887       1    0  19.0      0      0         2
888       3    0  28.0      1      2         2
889       1    1  26.0      0      0         0
890       3    1  32.0      0      0         1

[891 rows x 6 columns]

In [13]:
y = dataset.iloc[:,1]
y

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [14]:
#splitting the data into training and test set
#Changed the random state to 19 for better value accuracy
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.15, random_state = 19)
print(X_train.shape,y_train.shape)
print(X_test.shape,y_test.shape)

(757, 6) (757,)
(134, 6) (134,)


In [15]:
#Preprocessing the data
#NORMALIZING THE DATA
from sklearn import preprocessing
scaler = preprocessing.StandardScaler().fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)
X_test

array([[ 0.83159379,  0.75103235, -0.61743119, -0.48146746, -0.47648966,
         0.60075168],
       [ 0.83159379,  0.75103235, -0.06821606, -0.48146746, -0.47648966,
        -1.89797921],
       [ 0.83159379,  0.75103235, -0.22513467,  0.40748587, -0.47648966,
        -1.89797921],
       [ 0.83159379,  0.75103235, -0.06821606, -0.48146746, -0.47648966,
        -0.64861377],
       [-0.36520564,  0.75103235, -0.46051258, -0.48146746, -0.47648966,
         0.60075168],
       [ 0.83159379,  0.75103235, -0.06821606,  0.40748587, -0.47648966,
         0.60075168],
       [-1.56200507, -1.33150057, -0.53897188, -0.48146746,  1.94433364,
        -1.89797921],
       [ 0.83159379, -1.33150057,  1.50097   ,  0.40748587,  3.15474529,
         0.60075168],
       [ 0.83159379,  0.75103235,  0.87329558, -0.48146746, -0.47648966,
         0.60075168],
       [ 0.83159379,  0.75103235,  0.95175488,  1.2964392 , -0.47648966,
         0.60075168],
       [-0.36520564, -1.33150057,  0.32408045, -0.

In [16]:
# Model For Logistic Regression
from sklearn.linear_model import LogisticRegression
logr = LogisticRegression()
logr.fit(X_train,y_train)
y_pred = logr.predict(X_test)
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))

0.835820895522388


In [17]:
#Model for K nearest neighbours
from sklearn import neighbors
krange = np.arange(1,30,1)
for k in krange:
        knn = neighbors.KNeighborsClassifier(n_neighbors=k)
        knn.fit(X_train, y_train)
        y_pred = knn.predict(X_test)
        from sklearn.metrics import accuracy_score
        print('Neighbour:',k,accuracy_score(y_test,y_pred))        

Neighbour: 1 0.7761194029850746
Neighbour: 2 0.7985074626865671
Neighbour: 3 0.835820895522388
Neighbour: 4 0.8507462686567164
Neighbour: 5 0.8432835820895522
Neighbour: 6 0.8582089552238806
Neighbour: 7 0.8656716417910447
Neighbour: 8 0.8656716417910447
Neighbour: 9 0.835820895522388
Neighbour: 10 0.8582089552238806
Neighbour: 11 0.8432835820895522
Neighbour: 12 0.8656716417910447
Neighbour: 13 0.8582089552238806
Neighbour: 14 0.8582089552238806
Neighbour: 15 0.8582089552238806
Neighbour: 16 0.8656716417910447
Neighbour: 17 0.8656716417910447
Neighbour: 18 0.8582089552238806
Neighbour: 19 0.8507462686567164
Neighbour: 20 0.8507462686567164
Neighbour: 21 0.8432835820895522
Neighbour: 22 0.8507462686567164
Neighbour: 23 0.835820895522388
Neighbour: 24 0.8432835820895522
Neighbour: 25 0.8507462686567164
Neighbour: 26 0.835820895522388
Neighbour: 27 0.8432835820895522
Neighbour: 28 0.8432835820895522
Neighbour: 29 0.8432835820895522


In [18]:
print('Best model is k neigbors till now. Best value of k is 15 and is 0.865')

Best model is k neigbors till now. Best value of k is 15 and is 0.865


In [19]:
# Model for Support Vector Machine
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.values.reshape(len(y_test),1)),1))

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [0 1]
 [0 1]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 1]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 1]
 [0 1]
 [1 0]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]]
[[77  8]
 [16 33]]


0.8208955223880597

In [20]:
print("The accuracy score for support Vector machine is 0.820")

The accuracy score for support Vector machine is 0.820


In [21]:
#Model for Kernel SVM
#importing the SVC library
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.values.reshape(len(y_test),1)),1))

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [0 1]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]]
[[82  3]
 [16 33]]


0.8582089552238806

In [22]:
print("The accuracy values from Kernel SVM is 0.858")

The accuracy values from Kernel SVM is 0.858


In [23]:
#importing the library to perform naive bayes
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.values.reshape(len(y_test),1)),1))

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [0 0]
 [1 0]
 [1 1]
 [1 1]
 [0 1]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 1]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 1]
 [0 1]
 [1 0]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]]
[[73 12]
 [12 37]]


0.8208955223880597

In [24]:
print("The accuracy values from naive bayes is 0.820")

The accuracy values from naive bayes is 0.820


In [25]:
#importing the decisionTree Classifier library
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.values.reshape(len(y_test),1)),1))

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[0 0]
 [0 0]
 [1 0]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [1 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 1]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]]
[[79  6]
 [20 29]]


0.8059701492537313

In [26]:
print("The accuracy values from decision tree is 0.805")

The accuracy values from decision tree is 0.805


In [27]:
#importing library for random forest classification
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.values.reshape(len(y_test),1)),1))

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [1 0]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 1]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]]
[[76  9]
 [11 38]]


0.8507462686567164

In [28]:
print("The accuracy values from random forest is 0.850")

The accuracy values from random forest is 0.850


In [29]:
#Performing oneHot  encoding on Embarked
#from sklearn.compose import ColumnTransformer
#from sklearn.preprocessing import OneHotEncoder
#ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [5])], remainder='passthrough')
#X = np.array(ct.fit_transform(X))

#from sklearn.model_selection import train_test_split
#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 10)

#from sklearn.preprocessing import StandardScaler
#sc = StandardScaler()
#X_train = sc.fit_transform(X_train)
#X_test = sc.transform(X_test)

import tensorflow as tf
tf.__version__

#Intitializing the ANN
ann = tf.keras.models.Sequential()

#Addint the input layer and the firs hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

#addint the second hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

#Adding the output layer
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))


#compiling the ANN
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

#Training the ANN on Training Set
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.values.reshape(len(y_test),1)),1))
l = []
for i in y_pred:
    if i == False:
        l.append(0)
    else:
        l.append(1)

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(accuracy_score(y_test, y_pred))

Epoch 1/100
24/24 [==============================] - 0s 1ms/step - loss: 0.6305 - accuracy: 0.6380
Epoch 2/100
24/24 [==============================] - 0s 997us/step - loss: 0.6139 - accuracy: 0.6486
Epoch 3/100
24/24 [==============================] - 0s 1ms/step - loss: 0.6002 - accuracy: 0.6592
Epoch 4/100
24/24 [==============================] - 0s 1ms/step - loss: 0.5886 - accuracy: 0.6645
Epoch 5/100
24/24 [==============================] - 0s 1ms/step - loss: 0.5774 - accuracy: 0.6975
Epoch 6/100
24/24 [==============================] - 0s 1ms/step - loss: 0.5681 - accuracy: 0.7107
Epoch 7/100
24/24 [==============================] - 0s 1ms/step - loss: 0.5606 - accuracy: 0.7239
Epoch 8/100
24/24 [==============================] - 0s 997us/step - loss: 0.5531 - accuracy: 0.7332
Epoch 9/100
24/24 [==============================] - 0s 1ms/step - loss: 0.5471 - accuracy: 0.7464
Epoch 10/100
24/24 [==============================] - 0s 1ms/step - loss: 0.5413 - accuracy: 0.7517
Epoch

24/24 [==============================] - 0s 955us/step - loss: 0.4190 - accuracy: 0.8309
Epoch 83/100
24/24 [==============================] - 0s 979us/step - loss: 0.4185 - accuracy: 0.8283
Epoch 84/100
24/24 [==============================] - 0s 998us/step - loss: 0.4189 - accuracy: 0.8309
Epoch 85/100
24/24 [==============================] - 0s 1ms/step - loss: 0.4183 - accuracy: 0.8283
Epoch 86/100
24/24 [==============================] - 0s 1ms/step - loss: 0.4185 - accuracy: 0.8322
Epoch 87/100
24/24 [==============================] - 0s 1ms/step - loss: 0.4181 - accuracy: 0.8309
Epoch 88/100
24/24 [==============================] - 0s 1ms/step - loss: 0.4176 - accuracy: 0.8283
Epoch 89/100
24/24 [==============================] - 0s 1ms/step - loss: 0.4176 - accuracy: 0.8309
Epoch 90/100
24/24 [==============================] - 0s 1ms/step - loss: 0.4173 - accuracy: 0.8322
Epoch 91/100
24/24 [==============================] - 0s 1ms/step - loss: 0.4174 - accuracy: 0.8309
Epoch 9

In [30]:
print("Till now best is K nearest neighbour")

Till now best is K nearest neighbour


In [31]:
#Choosing the K nearest neighbour for prediction of survivours

#importing the test.csv dataset
test_dataset = pd.read_csv('test.csv')

#Importing the KNN library
#from sklearn import neighbors
#Training the model
#knn = neighbors.KNeighborsClassifier(n_neighbors=9)
#knn.fit(X_train, y_train)
#y_pred = knn.predict(X_test)

In [32]:
test_dataset

PassengerId  Pclass                                          Name  \
0            892       3                              Kelly, Mr. James   
1            893       3              Wilkes, Mrs. James (Ellen Needs)   
2            894       2                     Myles, Mr. Thomas Francis   
3            895       3                              Wirz, Mr. Albert   
4            896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)   
..           ...     ...                                           ...   
413         1305       3                            Spector, Mr. Woolf   
414         1306       1                  Oliva y Ocana, Dona. Fermina   
415         1307       3                  Saether, Mr. Simon Sivertsen   
416         1308       3                           Ware, Mr. Frederick   
417         1309       3                      Peter, Master. Michael J   

        Sex   Age  SibSp  Parch              Ticket      Fare Cabin Embarked  
0      male  34.5      0      0              330911    7.8292   NaN        Q  
1    female  47.0      1      0              363272    7.0000   NaN        S  
2      male  62.0      0      0              240276    9.6875   NaN        Q  
3      male  27.0      0      0              315154    8.6625   NaN        S  
4    female  22.0      1      1             3101298   12.2875   NaN        S  
..      ...   ...    ...    ...                 ...       ...   ...      ...  
413    male   NaN      0      0           A.5. 3236    8.0500   NaN        S  
414  female  39.0      0      0            PC 17758  108.9000  C105        C  
415    male  38.5      0      0  SOTON/O.Q. 3101262    7.2500   NaN        S  
416    male   NaN      0      0              359309    8.0500   NaN        S  
417    male   NaN      1      1                2668   22.3583   NaN        C  

[418 rows x 11 columns]

In [33]:
X_test = test_dataset.loc[:,[ 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch','Embarked']]
#'PassengerId',

In [34]:
X_test

Pclass     Sex   Age  SibSp  Parch Embarked
0         3    male  34.5      0      0        Q
1         3  female  47.0      1      0        S
2         2    male  62.0      0      0        Q
3         3    male  27.0      0      0        S
4         3  female  22.0      1      1        S
..      ...     ...   ...    ...    ...      ...
413       3    male   NaN      0      0        S
414       1  female  39.0      0      0        C
415       3    male  38.5      0      0        S
416       3    male   NaN      0      0        S
417       3    male   NaN      1      1        C

[418 rows x 6 columns]

In [35]:
#replacing all the null values of Age by the median of the data
X_test['Age'] = X_test['Age'].fillna(X['Age'].median())


#performing label Encoding on Sex and Embarked column
from sklearn.preprocessing import LabelEncoder

#Performing Label Encoding on Sex column
le_test = LabelEncoder()
X_test.iloc[:,1] = le_test.fit_transform(X_test.iloc[:,1])


#Performing Label Encoding on Embarked
le_embarked_test = LabelEncoder()
X_test.iloc[:,5] = le_embarked_test.fit_transform(X_test.iloc[:,5])

In [36]:
X_test

Pclass  Sex   Age  SibSp  Parch  Embarked
0         3    1  34.5      0      0         1
1         3    0  47.0      1      0         2
2         2    1  62.0      0      0         1
3         3    1  27.0      0      0         2
4         3    0  22.0      1      1         2
..      ...  ...   ...    ...    ...       ...
413       3    1  28.0      0      0         2
414       1    0  39.0      0      0         0
415       3    1  38.5      0      0         2
416       3    1  28.0      0      0         2
417       3    1  28.0      1      1         0

[418 rows x 6 columns]

In [37]:
#performing Normalization on X_test
from sklearn import preprocessing
scaler = preprocessing.StandardScaler().fit(X_train)
X_train = scaler.transform(X_train)
scaler_2 = preprocessing.StandardScaler().fit(X_test)
X_test = scaler_2.transform(X_test)
X_test

array([[ 0.87348191,  0.75592895,  0.37106201, -0.49947002, -0.4002477 ,
        -0.47091535],
       [ 0.87348191, -1.32287566,  1.35898508,  0.61699237, -0.4002477 ,
         0.70076689],
       [-0.31581919,  0.75592895,  2.54449275, -0.49947002, -0.4002477 ,
        -0.47091535],
       ...,
       [ 0.87348191,  0.75592895,  0.68719739, -0.49947002, -0.4002477 ,
         0.70076689],
       [ 0.87348191,  0.75592895, -0.14265798, -0.49947002, -0.4002477 ,
         0.70076689],
       [ 0.87348191,  0.75592895, -0.14265798,  0.61699237,  0.61989583,
        -1.64259759]])

In [44]:
#Importing the KNN library
from sklearn import neighbors
#Training the model
knn = neighbors.KNeighborsClassifier(n_neighbors=16)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
y_pred_ann = ann.predict(X_test)
y_pred_ann = (y_pred_ann>0.5)

In [45]:
y_pred

array([0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [47]:
l = []
for i in y_pred_ann:
    if i == False:
        l.append(0)
    else:
        l.append(1)
print(l)

[0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 

In [51]:
lst = {'PassengerId': test_dataset['PassengerId'], 'Survived': y_pred}
df = pd.DataFrame(lst)
lst2 =  {'PassengerId': test_dataset['PassengerId'], 'Survived': l}
df2= pd.DataFrame(lst2)

In [52]:
df

PassengerId  Survived
0            892         0
1            893         1
2            894         0
3            895         0
4            896         0
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

In [53]:
df.to_csv('submission101.csv')


In [54]:
df2.to_csv('annSubmission.csv')